In [10]:
from styleframe import StyleFrame
sf = StyleFrame({'a': [1, 2]})


sf.data_df.

0    1
1    2
Name: a, dtype: object

In [16]:
import pandas as pd
from styleframe import StyleFrame, Styler, utils

a = pd.DataFrame({'a': [1, 2], 'b': [1.1, 2.1]})
sa = StyleFrame(a)
red = Styler(bg_color=utils.colors.red)
sa.apply_style_by_indexes(indexes_to_style=[0], cols_to_style='a', styler_obj=red, overwrite_default_style=False)
sa.to_excel("sa.xlsx").save()
sa.data_df

   a    b
0  1  1.1
1  2  2.1

In [20]:
import pandas as pd
from styleframe import StyleFrame, Styler, utils

a = pd.DataFrame({'a': [1, 2], 'b': [1.1, 2.1]})

sa = StyleFrame(a)
red = Styler(bg_color=utils.colors.red)

b = pd.DataFrame({'a': [3, 4], 'b': [3.1, 4.1]})
sb = StyleFrame(b)

sa.apply_style_by_indexes(indexes_to_style=[0], cols_to_style='a', styler_obj=red, overwrite_default_style=False)
sb.apply_style_by_indexes(indexes_to_style=[1], cols_to_style='b', styler_obj=red, overwrite_default_style=False)
sa.to_excel("sa.xlsx").save()
sb.to_excel("sb.xlsx").save()

aplusb = sa.data_df.append(sb.data_df, ignore_index=True)
sa = StyleFrame(aplusb)
sa.to_excel("sa_plus_b.xlsx").save()
sa.data_df

/tmp/ipykernel_486431/592566677.py:17: FutureWarning:The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

   a    b
0  1  1.1
1  2  2.1
2  3  3.1
3  4  4.1

In [66]:
df = pd.read_excel('/home/vy/Downloads/sum_ICSR_2022_04_22.xlsx')
sa = StyleFrame(df)
sa.data_df

           Substance Group Reference database  ... Nullified?   Nullification date
0                 ACARBOSE             EMBASE  ...        nan                  NaT
1     ACETYLSALICYLIC ACID             EMBASE  ...        nan                  NaT
2     ACETYLSALICYLIC ACID             EMBASE  ...        nan                  NaT
3     ACETYLSALICYLIC ACID             EMBASE  ...        nan                  NaT
4     ACETYLSALICYLIC ACID             EMBASE  ...        nan                  NaT
...                    ...                ...  ...        ...                  ...
1471                   nan                nan  ...        nan                  NaT
1472                   nan                nan  ...        nan                  NaT
1473                   nan                nan  ...        nan                  NaT
1474                   nan                nan  ...        nan                  NaT
1475                   nan                nan  ...          Y  2018-10-31 00:00:00

[1476 rows x 30 columns]

In [67]:
# a = sa.data_df.iloc[0:3]
# type(a)
sa["Substance Group"].style.bg_color == utils.colors.yellow

0       False
1       False
2       False
3       False
4       False
        ...
1471    False
1472    False
1473    False
1474    False
1475    False
Length: 1476, dtype: bool

In [48]:
sa["Substance Group"].style.bg_color == utils.colors.yellow

0       False
1       False
2       False
3       False
4       False
        ...
1920    False
1921    False
1922    False
1923    False
1924    False
Length: 1925, dtype: bool